server.name: kibana
server.host: "0"
elasticsearch.url: http://{{hex.name}}-n1:9200
elasticsearch.username: elastic
elasticsearch.password: changeme
xpack.monitoring.ui.container.elasticsearch.enabled: true
